### ISSUE TITLE
压缩图片覆盖原始图

### ISSUE THREAD

**Issue by xiaocuyu** [SuperAL/splice#1]
默认情况下，不能把原始图覆盖吧，至少建个文件夹之类的

**Comment by SuperAL** [comment]
完全可以理解，但是因为提供了文件重命名的操作，还有文件地址输出位置的自定义，所以我想直接把这部分操作交由用户来自定义，不想写得太复杂。（还有因为我懒……）

**Comment by xiaocuyu** [comment]
👍 666
